---
galaxy_info:
  namespace: kode3tech
  role_name: podman
  author: Kode3Tech DevOps Team
  description: Install and configure Podman with rootless support
  company: Code3Tech

  issue_tracker_url: https://github.com/kode3tech/ansible-docker/issues

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy    # 22.04
        - noble    # 24.04
        - plucky   # 25.04
    - name: Debian
      versions:
        - bullseye # 11
        - bookworm # 12
        - trixie   # 13
    - name: EL
      versions:
        - "9"
        - "10"

  galaxy_tags:
    - podman
    - container
    - containerization
    - infrastructure
    - devops
    - deployment
    - oci

dependencies: []

# Collection dependencies (install via requirements.yml):
# - containers.podman >= 1.10.0
